POST http://localhost:8080/recipe/
Content-Type: application/json

{
  "name": "Наименование 2",
  "timeReady": 20,
  "ingredients": [
    {
      "name": "Ингредиент 3",
      "count": 10,
      "measureUnit": "шт."
    },
    {
      "name": "Ингредиент 4",
      "count": 500,
      "measureUnit": "гр."
    }
  ],
  "steps": [
    "Step 1",
    "Step 2",
    "Step 3"
  ]
}
###
PUT http://localhost:8080/recipe/1
Content-Type: application/json

{
  "name": "Новое измененное",
  "timeReady": 10,
  "ingredients": [
    {
      "name": "Ингредиент неизветный",
      "count": 10,
      "measureUnit": "шт."
    }
  ],
  "steps": [
    "Step 1",
    "Step 2"
  ]
}

###
GET http://localhost:8080/recipe/1
###
GET http://localhost:8080/recipe
###
GET http://localhost:8080/recipe/by/?ingredient=1
###
DELETE http://localhost:8080/recipe/1





###
POST http://localhost:8080/ingredient/
Content-Type: application/json

{
  "name": "Ингредиент 4",
  "count": 5,
  "measureUnit": "шт."
}
###
GET http://localhost:8080/ingredient/3
###
GET http://localhost:8080/ingredient
###
PUT http://localhost:8080/ingredient/3
Content-Type: application/json

{
  "name": "Ингредиент 3-новое",
  "count": 20,
  "measureUnit": "шт."
}
###
DELETE  http://localhost:8080/ingredient/2